AWSTemplateFormatVersion: 2010-09-09
Description: CloudTrail For GeneralTrail

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  # CloudTrail 作成
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: !Sub
        - ${SystemName}-${EnvType}-cloud-trail
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      S3BucketName:
        Fn::ImportValue: CloudTrailBucketName
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-cloud-trail
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
